Wunderbyte-GmbH/moodle-local_catquiz

classes/catquiz.php, classes/output/catcontextdashboard.php, classes/table/catcontext_table.php, lang/de/local_catquiz.php, lang/en/local_catquiz.php
With this change, the context table shows for each context the number of question attempts. This number is defined as the number of all question attempt steps that fall within the timespan defined by the context and have a fraction that is not null.
=> Show question attempts in CAT context table

classes/catquiz.php, version.php
This removes the parentheses from the `GROUP BY` clause.
=> GH-13 Fix: remove parentheses from SQL GROUP BY

classes/catquiz.php, classes/output/catscaledashboard.php, classes/table/testitems_table.php, lang/de/local_catquiz.php, lang/en/local_catquiz.php
This removes the model difficulty and status from the items tables, so that there is only one row per item. Before that, we had one row per model per item.
=> Revert adding model data to item table

classes/catcontext.php, classes/catmodel_info.php, classes/catquiz.php, classes/task/recalculate_cat_model_params.php
Adds a new function that gets the number of new responses since a given timepoint. Recalculation is now only performed if there is a new response associated to a CAT context and CAT scales.
The event that informs about recalculations now gets a correct number of updated items: a recalculation for an item is counted only once, even if its recalculated by more than one model.
Closes #155 
Closes #168
=> GH-155 Only recalculate params when needed

templates/feedback/debuginfo.mustache
Most of the functionality is already in develop. This just changes the styling of the link.
Closes #194
=> Use button for debug info CSV download

classes/output/attemptfeedback.php, classes/teststrategy/feedbackgenerator/customscalefeedback.php, classes/teststrategy/strategy/classicalcat.php, classes/teststrategy/strategy/inferallsubscales.php, classes/teststrategy/strategy/infergreateststrength.php, classes/teststrategy/strategy/inferlowestskillgap.php, classes/teststrategy/strategy/teststrategy_balanced.php, classes/teststrategy/strategy/teststrategy_fastest.php
This is more of a minimal example of how feedback generators can be configured on a per-strategy basis: by passing parameters via the constructor argument.
This is implemented here for the `customscalefeedback` class. If no argument is given, feedbacks are sorted by ascending person ability. However, this can be changed by passing a custom sort function, as for the `infergreateststrength` strategy.
Closes #184
=> GH-184 Configure feedback generators per strategy

classes/teststrategy/feedbackgenerator/debuginfo.php, classes/teststrategy/feedbackgenerator/graphicalsummary.php, classes/wb_middleware_runner.php
To prevent exhausting the memory, this removes both the `questions` and `original_questions` elements from the `$context` that is saved for each response during a quiz attempt. 
This means that now some data are missing in the debuginfo CSV output
=> Quickfix: remove cached questions for feedback

classes/teststrategy/preselect_task/addscalestandarderror.php, classes/teststrategy/preselect_task/mayberemovescale.php
had to change the default inf value because parsing to json isn't supported for INF
does this cause any problems @davidszkiba ?
=> Replace inf value

README.md, classes/catcontext.php, classes/teststrategy/feedbackgenerator/personabilities.php, lang/de/local_catquiz.php, lang/en/local_catquiz.php, templates/feedback/personabilities.mustache
=> neue charts

classes/catscale.php
If we lookup a catscale with a certain ID and there is none, raise an exception instead of returning null.
This prevents us from having to check if a catscale is null everytime we use the `return_catscale_object()` function.
Instead, the code that uses it can wrap the call within a try/catch block.
If we accidentally forget to do that, the exception message should make it easier to find the error.
=> Throw exception if catscale can not be found

classes/teststrategy/preselect_task/updatepersonability.php
This adds more information to the exception that is thrown if the ability can not be calculated due to missing item params.
This should help to debug #272
=> Add more information to exception

classes/catquiz.php, classes/catquiz_handler.php, classes/local/status.php, classes/output/attemptfeedback.php, classes/teststrategy/preselect_task/checkitemparams.php, classes/teststrategy/strategy.php, classes/teststrategy/strategy/classicalcat.php, classes/teststrategy/strategy/inferallsubscales.php, classes/teststrategy/strategy/infergreateststrength.php, classes/teststrategy/strategy/inferlowestskillgap.php, classes/teststrategy/strategy/teststrategy_balanced.php, classes/teststrategy/strategy/teststrategy_fastest.php, lang/de/local_catquiz.php, lang/en/local_catquiz.php
Instead of going to the point where an exception is raised, this adds a new pre-select task `checkitemparams` to check if we could perform the quiz. If not, an error is returned.
The feedback was changed as follows:
if an error message is returned and 0 messages were attempted, show the error message.
Sometimes we get an error message even if the quiz was executed, e.g. because there are no more questions. In this case we want to show the normal quiz feedback. That's why the error message is displayed only if the quiz returned an error *and* no questions were attempted.
Related to #272
=> Show message if quiz can not be started

classes/teststrategy/strategy/infergreateststrength.php, classes/teststrategy/strategy/teststrategy_balanced.php
This fixes errors about a missing standard error 'se' in the "infer greatest strength" and "balanced" teststrategies.
=> Fix: add SE before stopping quiz

classes/catquiz.php, classes/catquiz_handler.php, classes/output/attemptfeedback.php, classes/teststrategy/context/loader/questions_loader.php, classes/teststrategy/info.php, classes/teststrategy/preselect_task.php, classes/teststrategy/preselect_task/checkbreak.php, classes/teststrategy/preselect_task/checkpagereload.php, classes/teststrategy/preselect_task/filterbystandarderror.php, classes/teststrategy/preselect_task/maximumquestionscheck.php, classes/teststrategy/preselect_task/updatepersonability.php, classes/teststrategy/progress.php, classes/teststrategy/strategy.php, classes/teststrategy/strategy/classicalcat.php, classes/teststrategy/strategy/inferallsubscales.php, classes/teststrategy/strategy/infergreateststrength.php, classes/teststrategy/strategy/inferlowestskillgap.php, classes/teststrategy/strategy/teststrategy_balanced.php, classes/teststrategy/strategy/teststrategy_fastest.php, lang/de/local_catquiz.php, lang/en/local_catquiz.php, tests/behat/catquiz_settings.feature, tests/teststrategy/preselect_task/updatepersonability_test.php
Add code to handle
1. what happens when the maximum attempt time is exceeded for an item
2. what happens when the page is reloaded
depending on the user session, this leads to different results:
1. page is reloaded, question time not exceeded -> show the same question again
2. page is reloaded, question time is exceeded and the user session changed -> show a different question and do not count the previous one
3. page is reloaded, question time is exceeded and user is in the same session -> manually enter a wrong answer for the previous question and display a new one
4. page is reloaded, question time is exceeded, user session is the same and we have an answer -> nothing we can do...
For more details, see also #311 
Closes #311
=> Dev david issue 311

.github/workflows/moodle-plugin-ci.yml
I updated our mirror of the adaptivequiz subplugin and removed the catquiz subplugin there.
This means, it has to be installed separately now.
This PR contains the changes to do this automatically when running Github actions.
Note: this includes branch `catmodel_subplugins_with_mod_form_reload_400 ` , which can work with Moodle 4.0.
=> Extract catmodel subplugin

classes/teststrategy/preselect_task/checkitemparams.php
I had an empty catscale in the db, so this error occured and no quiz could be played.
but other scales contained items. 
maybe should we adjust the handling for this case?
=> bugfix no items found in scale error

classes/catquiz.php, classes/teststrategy/progress.php
If a user clicks the Submit button without providing an answer, count the response as wrong.
=> GH-359 Consider unanswered questions as being wrong

classes/local/status.php, classes/teststrategy/progress.php, classes/teststrategy/strategy.php
If the maximum time for an attempt is exceeded, do not even start to execute the pre-select tasks but instead return immediately. While most other things are implemented as pre-select tasks, in this case it is easier to return early because we do not want to generate any feedback for a question that would be selected and would skip the remaining pre-select tasks anyway.
=> GH-329 Enforce max attempt time

classes/teststrategy/feedbackgenerator/comparetotestaverage.php, classes/teststrategy/feedbackgenerator/personabilities.php, templates/feedback/comparetotestaverage.mustache
Closes #314 
See that issue for more details.
In short: some parts of the feedback are now hidden if we have not enough data and I checked that the numbers are correct. Also, it uses the test *average* instead of the median now to show the ability of peer students
=> Dev david issue 314

classes/catquiz.php, classes/form/item_model_override_selector.php, classes/output/testitemdashboard.php, templates/tabs/tab_models.mustache
See #318 
This changes the item override form so that:
- no parameters are displayed if the status is set to "not yet calculated"
- textfields are disabled if the value is set to "calculated"
Also, the *Status* card on the same page now also shows the model that corresponds to the selected status.
=> Dev david issue 318

classes/catquiz.php, classes/feedback/feedbackclass.php
We tried to read the ability after from a non-existent array key and therefore always used null as fallback value. This is fixed here.
=> GH-425 Fix: save ability after each question

classes/catquiz.php, classes/catquiz_handler.php, classes/output/attemptfeedback.php, classes/teststrategy/context/loader/personability_loader.php, classes/teststrategy/context/loader/progress_loader.php, classes/teststrategy/context/loader/questions_loader.php, classes/teststrategy/feedbackgenerator.php, classes/teststrategy/feedbackgenerator/comparetotestaverage.php, classes/teststrategy/feedbackgenerator/customscalefeedback.php, classes/teststrategy/feedbackgenerator/graphicalsummary.php, classes/teststrategy/feedbackgenerator/learningprogress.php, classes/teststrategy/feedbackgenerator/personabilities.php, classes/teststrategy/feedbacksettings.php, classes/teststrategy/preselect_task/checkitemparams.php, classes/teststrategy/preselect_task/strategydeficitscore.php, classes/teststrategy/progress.php, tests/teststrategy/feedbackgenerator/customscalefeedback_test.php, tests/teststrategy/feedbackgenerator/personabilities_test.php
If the settings of a quiz change, this does not affect attempts that are not yet finished - they continue to use the old settings from the attempt start.
=> Use quiz settings from attempt start

classes/catquiz.php, classes/catquiz_handler.php, classes/teststrategy/strategy.php
The endtime is now set to the last point in time that was relevant for the result. The timemodified shows the time point of the last interaction, even if it was after the time limit.
=> GH-458 Update endtime and timemodified of attempts

classes/catquiz.php, classes/output/attemptfeedback.php, lang/de/local_catquiz.php, lang/en/local_catquiz.php, settings.php, tests/catquiz_test.php, tests/output/attemptfeedback_test.php, tests/teststrategy/strategy_test.php, version.php
Closes #479 
- By default, enrol user only to courses and groups defined for the primary scale.
- Add a plugin setting to get the old behaviour: enrol into courses and groups of _all_ matching scales.
Refactorings:
since we already have the information about which scale is primary in the attempt data, we re-use them
1. There is a new method `get_courses_to_enrol` in attemptfeedback.php
2. There is a new method `get_groups_to_enrol` in attemptfeedback.php
These methods are only responsible for detecting the courses and groups.
Enrolment and sending of messages is still handled in the `catquiz` class as before.
I added `attemptfeedback_test` to check the course/group enrolment works as expected.
=> Update course enrolment

classes/teststrategy/feedbackgenerator/debuginfo.php
Somehow [1], in the debuginfo feedback generator, the fisherinformation is overwritten. When this happens and the cache is deleted, the progress class will read the fisherinformation from the database where it gets the overwritten value. That value might now be a string like "NA" which causes errors.
1: the fisherinformation is overwritten because it is part of the `lastquestion` object in the `$newdata` array. Objects are passed by reference, and therefore changing the value in the feedback generator also changes it in outer scopes.
=> GH-537 Do not overwrite fisherinfo

classes/teststrategy/feedbackgenerator/personabilities.php, templates/feedback/personabilities.mustache, tests/teststrategy/feedbackgenerator/personabilities_test.php
Even if reporting is disabled for the main scale, it should still be shown as reference in the personabilities feedback.
=> GH-566 Fix: always display reference scale

classes/teststrategy/feedbackgenerator/comparetotestaverage.php, lang/de/local_catquiz.php, lang/en/local_catquiz.php, templates/feedback/comparetotestaverage.mustache
Instead of hiding the whole feedback text, just do not display the feedback "you are better than XX% other participants" if XX is less than 15.
=> GH-575 Fix feedback text for results in low quantiles

classes/output/catscales.php
O(n^2+) => O(n)
Es wurden auf dem LTI-Server bei ca. 350 CAT-Skalen ca. 12000-mal die Subscription-Tabelle abgefragt, insgesamt wurden 120 MB (!) an Anfragen an die DB gestellt!
vorher:
nachher:
=> 584 fix bad looping in catscale.php

classes/event/catquiz_event_base.php
It is possible, that the event data are empty. In this case, return null.
Closes #571
=> GH-571 Allow null `other` event data

classes/teststrategy/info.php
Closes #541 
The minquestions field was always overwritten by the default value. This is fixed here.
=> GH-541 Fix min questions quiz settings field

classes/output/catquizstatistics.php, templates/catscaleshortcodes/catscalestatistics.mustache, version.php
Fixes #643 
Zeigt eine Meldung an, wenn die Berechtigung zum Download eines Quiz Attempts als CSV fehlt:
Die checks in `export_shortcode_csv.php` sind weiterhin vorhanden, falls jemand direkt über die URL auf den Export zugreift.
=> Dev david issue 643

classes/catscale.php
With the new DB structure, where each item points to its active item parameter via the `activeparamid` field, we have to duplicate items during import whenever itemparams are duplicated.
Closes #663
=> Dev david issue 663

classes/catquiz_handler.php, classes/feedback/feedbackclass.php, classes/teststrategy/feedbackgenerator/customscalefeedback.php, lib.php, tests/behat/catquiz_settings.feature, tests/behat/catscales_attempt_management.feature, tests/teststrategy/feedbackgenerator/customscalefeedback_test.php
Save images from the draft area and rewrite the image URL before returning it as part of the feedback content.
Closes #639
=> GH-639 Save images from quiz settings

classes/catquiz.php, classes/catquiz_handler.php, classes/feedback/feedbackclass.php, classes/testenvironment.php, classes/teststrategy/feedbackgenerator/customscalefeedback.php, lang/de/local_catquiz.php, lang/en/local_catquiz.php
Images are loaded into the draft area and displayed in the html forms. They are also displayed in shortcodes and the quiz feedback.
Note: when a quiz is saved for the first time, we do not have access to the context module at the time when we want to save the iamges. This means, that at the moment, images are only saved to the database when an existing quiz is updated, but not when a quiz is first created. We show a warning box to inform users about that.
=> GH-639 Fix saving of feedback images

.github/workflows/moodle-plugin-ci-pullreq.yml, .github/workflows/moodle-plugin-ci-push.yml, tests/behat/catquestions_model_override.feature
On pushes, the matrix is smaller (two PHP versions, 7.4 and 8.2, on two moodle version, 4.1 and 4.4.
On pull requests and tag pushes (version tags x.y.z or date tags like e.g. 202401010100), the test matrix is the same as before.
=> Reduce github actions

classes/shortcodes.php
Instead of getting the course ID from the `id` query parameter, we get it from the global `$COURSE` object. This is more robust. The previous approach did not work if a user visited a different page that also had an `id` query parameter (e.g. section.php?id=123).
Closes #669
=> GH-669 Fix retrieval of catquizstatistics course ID

classes/feedback/feedbackclass.php
The hidden fields that contain the scale boundaries did not have the value set and therefore used the default fallback. This is fixed here.
=> GH-655 Fix: Save changed upper/lower scale boundaries in quiz settings

classes/local/model/model_item_param_list.php, version.php
This makes the code more robust: If there exist multiple question versions, we try to remove older question versions from the scale it should be assigned to. However, it is possible that the scale it should be assigned to does not exist yet. This is accounted for in the updated code.
=> GH-720 Fix import error with multiple question versions

catmodel/grm/classes/grm.php, catmodel/grmgeneralized/classes/grmgeneralized.php, catmodel/pcm/classes/pcm.php, catmodel/pcmgeneralized/classes/pcmgeneralized.php
In multiparam models, `get_difficulty()` will return the value of `calculate_mean_difficulty()`.
Closes #706
=> GH-706 Update get_difficulty() for multiparam models

classes/teststrategy/feedbackgenerator.php
Closes #760 
It is possible, that `$selectedscaleid` is never assigned a value. In order for it to still be declared, it is initialized to `null`.
=> GH-760 Fix possibly undeclared variable

classes/output/catquizstatistics.php, classes/shortcodes.php, classes/teststrategy/feedback_helper.php
If we try to determine the range for a given scale in a quiz but those values do not exist, fallback to not displaying the range legend.
=> GH-719 statistics shortcode catches error for missing setting

lang/de/local_catquiz.php, lang/en/local_catquiz.php, manage_catscales.php
There should actually always be a default context in the database. If it is missing, it indicates a problem with the installation. This shows a warning notification to inform the user to double-check that the installation process was completed successfully.
=> GH-762 Show message if default context is missing

classes/output/catscaledashboard.php
If a chart contains more than N data points (100 by default), we filter out values at most N values.
=> GH-751 Reduce values used to display charts

classes/catcontext.php, classes/table/catcontext_table.php, lang/de/local_catquiz.php, lang/en/local_catquiz.php
This was probably a copy/paste error: the delete button tried to delete a testenvironment with the given ID, not a CAT context. This is fixed here.
Closes #767
=> GH-767 Fix deletion of CAT contexts

classes/teststrategy/feedbackgenerator/customscalefeedback.php
A previous commit converted the entries of `$catscales` to objects. Therefore, we have to explicitely get the numeric ID with `$a->id` or `$b->id`.
=> GH-792 Fix array offset

classes/catquiz.php
@ralferlebach mit meinen daten wird hier kein fehler geworfen. können wir uns vielleciht die daten bei dir in der db mal anschauen, woher die duplikate in der id der skala kommt, wenn man folgendes sql ausführt:
SELECT * FROM m_local_catquiz_catscales s
JOIN m_local_catquiz_catcontext cc ON s.contextid = cc.id
SELECT s.id, MIN(cc.name) as example_column
WHERE s.contextid IS NOT NULL;
=> Bugfix: Make sure first column in sql is unique #814
