Wunderbyte-GmbH/moodle-local_catquiz

classes/catquiz.php, classes/output/catscaledashboard.php, classes/table/student_stats_table.php, db/caches.php, lang/de/local_catquiz.php, lang/en/local_catquiz.php, templates/catscaledashboard.mustache
- Additional column for test items: # of attempts in the selected context (qas fraction not null)
- Additional tab: List of Students: Number of questions attempted (first name, last name, count)
Closes #7
=> UI: update catscaledashboard

classes/catquiz_handler.php
This function should fetch the appropriate question in the future. For now, it just returns a single question ID so that we can test the integration.
=> Add dummy fetch_question_id() function

catmodel/demo/classes/demo.php, catmodel/raschbirnbauma/classes/raschbirnbauma.php, catmodel/raschbirnbaumb/classes/raschbirnbaumb.php, catmodel/raschbirnbaumc/classes/raschbirnbaumc.php, catmodel/raschbirnbaumc/db/install.php, catmodel/raschbirnbaumc/db/upgrade.php, catmodel/raschbirnbaumc/version.php, classes/catcalc.php, classes/local/model/model_item_param.php, classes/local/model/model_item_param_list.php, classes/local/model/model_model.php
=> Handle multiple item parameters

catmodel/demo/classes/demo.php, catmodel/raschbirnbauma/classes/raschbirnbauma.php, catmodel/raschbirnbaumb/classes/raschbirnbaumb.php, catmodel/raschbirnbaumc/classes/raschbirnbaumc.php, classes/catcontext.php, classes/catquiz.php, classes/catquiz_handler.php, classes/catscale.php, classes/data/dataapi.php, classes/local/model/model_model.php, classes/local/result.php, classes/local/status.php, classes/output/catscaledashboard.php, classes/table/testitems_table.php, classes/teststrategy/teststrategy_base.php, classes/teststrategy/teststrategy_fastest.php, db/caches.php, lang/de/local_catquiz.php, lang/en/local_catquiz.php
=> Work on test strategies

classes/catscale.php, classes/local/model/model_person_ability_estimator_demo.php, classes/local/status.php, classes/table/testitems_table.php, lang/de/local_catquiz.php, lang/en/local_catquiz.php
=> GH-39 Forbid adding item to parent/sub scale

classes/catquiz.php, classes/catquiz_handler.php, classes/teststrategy/context/loader/pilotquestions_loader.php, classes/teststrategy/info.php, classes/teststrategy/item_score_modifier/ispilot.php, classes/teststrategy/item_score_modifier/lasttimeplayedpenalty.php, classes/teststrategy/item_score_modifier/strategybalancedscore.php, classes/teststrategy/item_score_modifier/strategyfastestscore.php, classes/teststrategy/item_score_modifier/strategyrandom.php, classes/teststrategy/strategy.php, classes/teststrategy/strategy/teststrategy_pilot.php, db/caches.php, lang/de/local_catquiz.php, lang/en/local_catquiz.php, lib.php
Handle pilot questions as described in #41
=> Pilot questions first part

classes/catquiz.php, classes/catquiz_handler.php, classes/local/model/model_item_param_list.php, classes/local/model/model_strategy.php, classes/local/status.php, classes/output/testitemdashboard.php, classes/teststrategy/item_score_modifier/updatepersonability.php, classes/teststrategy/strategy.php, classes/teststrategy/strategy/teststrategy_balanced.php, classes/teststrategy/strategy/teststrategy_fastest.php, classes/teststrategy/strategy/teststrategy_pilot.php, db/caches.php, lang/de/local_catquiz.php, lang/en/local_catquiz.php
See #43 for details
Closes #43
=> Teststrategy abort

catmodel/raschbirnbauma/classes/raschbirnbauma.php, catmodel/raschbirnbaumb/classes/raschbirnbaumb.php, catmodel/raschbirnbaumc/classes/raschbirnbaumc.php, classes/catcalc.php, classes/catcalc_interface.php, classes/local/model/model_model.php, classes/local/model/model_raschmodel.php
See #77 for details
Closes #77
=> Refactor to support non-dichotomous responses

catmodel/raschbirnbauma/classes/raschbirnbauma.php, catmodel/raschbirnbaumb/classes/raschbirnbaumb.php, catmodel/raschbirnbaumc/classes/raschbirnbaumc.php
Implemented Trusted Regions as
* Filter
*  Overlay Functions for 1st and 2nd log derivatives
This resolves issue #48 
Please check for typos and params. Also please define abstract functions for 
* get_log_tr_jacobian()
* get_log_tr_hessian()
and add comments as requested by moodle standards.
=> Trusted Regions in 1PL, 2PL, 3PL implemented

classes/catcalc.php, classes/output/attemptfeedback.php, classes/teststrategy/context/loader/personability_loader.php, classes/teststrategy/preselect_task/filterforlowestsubscale.php, classes/teststrategy/preselect_task/updatepersonability.php, classes/teststrategy/preselect_task/updatepersonabilitytesting.php, classes/teststrategy/strategy.php, lang/de/local_catquiz.php, lang/en/local_catquiz.php, lib.php, tests/catcalc_test.php, tests/teststrategy/preselect_task/updatepersonability_test.php, tests/teststrategy/strategy/teststrategy_fastest_test.php
=> Dev david issue 86

classes/catquiz_handler.php, classes/teststrategy/context/loader/personability_loader.php, classes/teststrategy/preselect_task/filterforlowestsubscale.php, classes/teststrategy/preselect_task/filterforsubscale.php, classes/teststrategy/preselect_task/filterforsubscaletesting.php, classes/teststrategy/strategy/infergreateststrength.php, classes/teststrategy/strategy/inferlowestskillgap.php, lang/de/local_catquiz.php, lang/en/local_catquiz.php, tests/teststrategy/preselect_task/filterforsubscale_test.php
=> Infer subscale with greatest strength

catmodel/raschbirnbaumc/classes/raschbirnbaumc.php, tests/catcalc_test.php
=> Dev david issue 114

catmodel/demo/classes/demo.php, catmodel/web_raschbirnbauma/classes/web_raschbirnbauma.php, classes/catcontext.php, classes/catquiz.php, classes/form/item_model_override_selector.php, classes/local/model/model_item_param_list.php, classes/local/model/model_model.php, classes/local/model/model_raschmodel.php, classes/local/model/model_strategy.php, classes/teststrategy/preselect_task/removeplayedquestions.php, classes/teststrategy/preselect_task/updatepersonability.php
=> Dev david issue 128

classes/catquiz.php, classes/output/attemptfeedback.php, classes/teststrategy/feedbackgenerator.php, classes/teststrategy/feedbackgenerator/comparetotestaverage.php, classes/teststrategy/feedbackgenerator/customscalefeedback.php, classes/teststrategy/feedbackgenerator/debuginfo.php, classes/teststrategy/feedbackgenerator/personabilities.php, classes/teststrategy/feedbackgenerator/pilotquestions.php, classes/teststrategy/feedbackgenerator/questionssummary.php, classes/teststrategy/strategy/inferallsubscales.php
=> Refactor feedback generator classes

classes/catquiz.php, classes/catquiz_handler.php, classes/output/attemptfeedback.php, classes/output/catscalemanager/managecatscaledashboard.php, classes/output/catscalemanager/quizattempts/quizattemptsdisplay.php, classes/shortcodes.php, classes/table/quizattempts_table.php, classes/teststrategy/context/loader/personability_loader.php, classes/teststrategy/context/loader/questions_loader.php, classes/teststrategy/feedbackgenerator.php, classes/teststrategy/feedbackgenerator/comparetotestaverage.php, classes/teststrategy/feedbackgenerator/customscalefeedback.php, classes/teststrategy/feedbackgenerator/debuginfo.php, classes/teststrategy/feedbackgenerator/personabilities.php, classes/teststrategy/feedbackgenerator/pilotquestions.php, classes/teststrategy/feedbackgenerator/questionssummary.php, classes/teststrategy/info.php, classes/teststrategy/strategy.php, db/access.php, db/caches.php, db/shortcodes.php, lang/de/local_catquiz.php, lang/en/local_catquiz.php, styles.css, templates/attemptfeedback.mustache, templates/catscalemanager/managecatscaledashboard.mustache, templates/catscalemanager/quizattempts/quizattemptsdisplay.mustache, version.php
=> Allow viewing past quiz attempts

catmodel/demo/classes/demo.php, catmodel/raschbirnbauma/classes/raschbirnbauma.php, catmodel/raschbirnbaumb/classes/raschbirnbaumb.php, catmodel/raschbirnbaumc/classes/raschbirnbaumc.php, catmodel/web_raschbirnbauma/classes/web_raschbirnbauma.php, classes/catcalc.php, classes/catcalc_ability_estimator.php, classes/catcalc_item_estimator.php, classes/local/model/model_item_response.php, classes/local/model/model_model.php, classes/local/model/model_person_param.php, classes/local/model/model_person_param_list.php, classes/local/model/model_raschmodel.php, classes/local/model/model_responses.php, classes/teststrategy/preselect_task/fisherinformation.php, tests/catcalc_test.php
This contains the changes of Ralf's #149 pull request and adds some changes on top to integrate it with the current code base.
Closes #149
=> Update raschbirnbaum models with refactorings

breakinfo.php, classes/catquiz_handler.php, classes/output/breakinfo.php, classes/teststrategy/feedbackgenerator/debuginfo.php, classes/teststrategy/info.php, classes/teststrategy/preselect_task/checkbreak.php, classes/teststrategy/strategy.php, classes/teststrategy/strategy/inferallsubscales.php, classes/teststrategy/strategy/infergreateststrength.php, classes/teststrategy/strategy/inferlowestskillgap.php, classes/teststrategy/strategy/teststrategy_balanced.php, classes/teststrategy/strategy/teststrategy_fastest.php, lang/de/local_catquiz.php, lang/en/local_catquiz.php, templates/breakinfo.mustache
=> Dev david issue 142

classes/catquiz_handler.php, classes/teststrategy/context/loader/questions_loader.php, classes/teststrategy/feedbackgenerator/customscalefeedback.php, classes/teststrategy/feedbackgenerator/debuginfo.php, classes/teststrategy/info.php, classes/teststrategy/preselect_task/addscalestandarderror.php, classes/teststrategy/preselect_task/fisherinformation.php, classes/teststrategy/preselect_task/mayberemovescale.php, classes/teststrategy/preselect_task/strategybalancedscore.php, classes/teststrategy/preselect_task/strategyfastestscore.php, classes/teststrategy/strategy/inferallsubscales.php, lang/de/local_catquiz.php, lang/en/local_catquiz.php, templates/feedback/debuginfo.mustache, tests/teststrategy/strategy/teststrategy_fastest_test.php
=> Dev david issue 85

classes/catcalc.php, classes/local/model/model_responses.php, classes/teststrategy/preselect_task/updatepersonability.php, classes/teststrategy/preselect_task/updatepersonabilitytesting.php, classes/teststrategy/strategy/inferlowestskillgap.php, tests/local/model/model_person_ability_estimator_catcalc_test.php, tests/teststrategy/preselect_task/updatepersonability_test.php
=> Dev david fix tests

classes/output/attemptfeedback.php, classes/teststrategy/feedbackgenerator/comparetotestaverage.php
See #180 for details
Closes #180
=> Dev david issue 180

classes/teststrategy/feedbackgenerator/debuginfo.php
=> Fix debuginfo errors

classes/catquiz.php
Ich habe eine neue Funktion hinzugefügt, welche ich für Adele benötige.
=> New Function: get all parent scales

classes/catquiz.php, classes/output/attemptfeedback.php, classes/output/catscalemanager/quizattempts/quizattemptsdisplay.php, classes/shortcodes.php, classes/teststrategy/context/loader/progress_loader.php, classes/teststrategy/feedbackgenerator.php, classes/teststrategy/feedbackgenerator/comparetotestaverage.php, classes/teststrategy/feedbackgenerator/customscalefeedback.php, classes/teststrategy/feedbackgenerator/debuginfo.php, classes/teststrategy/feedbackgenerator/graphicalsummary.php, classes/teststrategy/feedbackgenerator/personabilities.php, classes/teststrategy/feedbackgenerator/pilotquestions.php, classes/teststrategy/feedbackgenerator/questionssummary.php, classes/teststrategy/preselect_task/updatepersonability.php, classes/teststrategy/progress.php, classes/teststrategy/strategy.php, tests/behat/catscales_modadaptivequiz.feature, tests/behat/catscales_modadaptivequiz_shortcodes.feature, tests/teststrategy/strategy_test.php
=> Fix: do not lose attemptfeedback if caches are cleared

classes/catquiz_handler.php
Stores the adaptivequiz endtime and number of played items in the DB table.
*Note:* the adaptivequiz plugin has to be updated as well
Closes #324
=> Save endtime in attempts table

README.md
@ralferlebach wir haben heute begonnen, das readme zu aktualisieren, damit eine ausführliche und für laien möglichst verständliche beschreibung teil der moodle einreichung wird, wie hier angefordert: https://moodledev.io/general/community/plugincontribution/checklist#plugin-descriptions
wir wären dir dankbar, wenn du darüber schauen, korrigieren und ergänzen könntest!
=> GH-366 prepare readme

classes/table/quizattempts_table.php
Fixes the anchor tag and removes unused GET parameters from the link
=> Fix link to quiz attempt

classes/table/catscalequestions_table.php
Das entfernt nur den edit action button aus der questions Tabelle da man bereits über die details view die item parameter editieren kann.
=> Remove edit button

classes/teststrategy/preselect_task/maximumquestionscheck.php
Fix an error that occured when only the first question was answered but the rest was skipped
Closes #359
=> Dev david issue 359

classes/catquiz.php, classes/messages.php, classes/output/attemptfeedback.php, lang/de/local_catquiz.php, lang/en/local_catquiz.php, show_attemptfeedback.php, templates/attemptfeedback.mustache, tests/catquiz_test.php
There is still a codestyle error because in the php unit tests, the expected return string exceeds the max. length of line.
maybe do you have a recommendation for this @davidszkiba  ?
=> Gh 268 notify users about enrolment

tests/catquiz_test.php
Closes #407
This adds a new test to check if a user is added to a course and group depending on the person ability and quiz settings.
=> Test user enrolment

classes/teststrategy/feedbacksettings.php
Bugfix for se is inf. standarderror
=> Bugfix: se is inf

classes/catquiz.php, classes/output/attemptfeedback.php, classes/teststrategy/progress.php, db/install.xml, db/upgrade.php, version.php
=> Reduce data stored in attempts table

classes/teststrategy/feedbackgenerator/graphicalsummary.php
Closes #463 
Only displays the global scale and the primary scale. If the primary scale IS the global scale, only one series is displayed.
=> Cleanup question summary chart

classes/catquiz.php
=> GH-459 Save attempted questions after every step

classes/teststrategy/feedbackgenerator/comparetotestaverage.php
=> Comparetotestaverage: always use global scale as reference

catmodel/grm/lang/de/catmodel_grm.php, catmodel/grm/lang/en/catmodel_grm.php, catmodel/grm/version.php, catmodel/grmgeneralized/classes/grmgeneralized.php, catmodel/grmgeneralized/lang/de/catmodel_grmgeneralized.php, catmodel/grmgeneralized/lang/en/catmodel_grmgeneralized.php, catmodel/grmgeneralized/settings.php, catmodel/grmgeneralized/version.php, catmodel/mixedraschbirnbaum/classes/mixedraschbirnbaum.php, catmodel/mixedraschbirnbaum/tests/mixedraschbirnbaum_test.php, catmodel/pcm/lang/de/catmodel_pcm.php, catmodel/pcm/lang/en/catmodel_pcm.php, catmodel/pcm/version.php, catmodel/rasch/classes/rasch.php, catmodel/rasch/tests/rasch_test.php, catmodel/raschbirnbaum/classes/raschbirnbaum.php, catmodel/raschbirnbaum/tests/raschbirnbaum_test.php, classes/catscale.php, classes/local/model/model_model.php, classes/local/model/model_strategy.php, classes/teststrategy/feedbackgenerator/learningprogress.php, classes/teststrategy/feedbackgenerator/personabilities.php, classes/teststrategy/preselect_task/filterbystandarderror.php, classes/teststrategy/preselect_task/fisherinformation.php, lib.php, tests/model_raschmodel_test.php, tests/teststrategy/feedbackgenerator/personabilities_test.php
This contains new model classes for polytomous models provided by @ralferlebach and some refactorings related to that.
=> Polytomous models

classes/catquiz.php, classes/catquiz_handler.php, classes/local/result.php, classes/local/status.php
=> Dev david issue 460

classes/catquiz.php, classes/output/catquizstatistics.php, classes/shortcodes.php, classes/teststrategy/context/loader/personability_loader.php, classes/teststrategy/feedback_helper.php, classes/teststrategy/feedbackgenerator/learningprogress.php, classes/teststrategy/preselect_task/firstquestionselector.php, lang/de/local_catquiz.php, lang/en/local_catquiz.php, templates/catscaleshortcodes/catscalestatistics.mustache
Not all charts are implemented yet, but this merges the current state into develop
=> Catquiz statistics update

classes/catquiz.php, classes/form/edit_catcontext.php, classes/output/testitemdashboard.php, classes/table/catcontext_table.php, classes/table/catscalequestions_table.php, templates/tabs/tab_models.mustache, tests/behat/catscales_import.feature
=> Dev david issue 410

classes/teststrategy/feedback_helper.php, classes/teststrategy/feedbackgenerator.php, classes/teststrategy/feedbackgenerator/comparetotestaverage.php, classes/teststrategy/feedbackgenerator/customscalefeedback.php, classes/teststrategy/feedbackgenerator/debuginfo.php, classes/teststrategy/feedbackgenerator/graphicalsummary.php, classes/teststrategy/feedbackgenerator/learningprogress.php, classes/teststrategy/feedbackgenerator/personabilities.php, classes/teststrategy/strategy/teststrategy_fastest.php, lang/de/local_catquiz.php, lang/en/local_catquiz.php, styles.css, templates/attemptfeedback.mustache, templates/feedback/comparetotestaverage.mustache, templates/feedback/debuginfo.mustache, templates/feedback/graphicalsummary.mustache, templates/feedback/learningprogress.mustache, templates/feedback/personabilities.mustache, tests/teststrategy/feedbackgenerator/customscalefeedback_test.php, tests/teststrategy/feedbackgenerator/personabilities_test.php
=> Dev david issue 517

classes/catquiz.php
=> Dev david issue 539

classes/output/attemptfeedback.php, lang/de/local_catquiz.php, lang/en/local_catquiz.php, templates/attemptfeedback.mustache
Closes #577 
Screenshots in #577
=> Dev david issue 577

lang/de/local_catquiz.php
Sprachdatei aktualisiert:
* kohärente Bezeichnungen (z.B. Fähigkeits-Wert)
* Bereinigung noch nicht gefixter Grafik-Labels
* typographisch korrekte Anführungszeichen
=> Update Language Strings

classes/catcontext.php, classes/catquiz.php, classes/local/model/model_model.php, classes/task/recalculate_cat_model_params.php
=> GH-568 Fix error during param calculation

classes/catcontext.php, classes/catmodel_info.php, classes/local/model/model_person_ability_estimator_catcalc.php, classes/local/model/model_person_param.php, classes/local/model/model_person_param_list.php, classes/local/model/model_raschmodel.php, classes/local/model/model_responses.php, classes/local/model/model_strategy.php, classes/output/catscales.php, tests/model_raschmodel_test.php
=> Dev david issue 580

classes/catquiz.php, classes/catscale.php, classes/data/catscale_structure.php, classes/local/model/model_item_param_list.php, classes/local/model/model_person_param.php, classes/local/model/model_person_param_list.php, classes/local/model/model_responses.php, classes/output/attemptfeedback.php, classes/teststrategy/feedbackgenerator.php, classes/teststrategy/feedbackgenerator/graphicalsummary.php, classes/teststrategy/feedbackgenerator/personabilities.php, classes/teststrategy/preselect_task/checkitemparams.php, classes/teststrategy/preselect_task/firstquestionselector.php, classes/teststrategy/preselect_task/updatepersonability.php, classes/teststrategy/progress.php, db/caches.php, db/install.xml, db/upgrade.php, tests/teststrategy/feedbackgenerator/personabilities_test.php
Closes #569 
Loading of the first and last page is still slow, but this will be fixed in #584
=> Dev david issue 569

classes/catquiz.php
Mit dem Merge wird #611 geschlossen.
=> GH-611 Fix SQL to view and edit scale items

db/upgrade.php, version.php
Ist bereits durch ein Update auf LTI für MariaDB funktionsgeprüft, bitte dennoch den Moodle-Codechecker etc. drüberlaufen lassen. Danke
=> 584 update catquiz items auch auch für ältere Kontexte + Fix Typo in upgrade.php

classes/local/model/model_item_param_list.php, tests/fixtures/simulation_beta.csv, tests/teststrategy/strategy_test.php
=> Dev david issue 508

classes/event/attempt_completed.php
=> Fange leere Ergebnisse ab.

classes/local/model/model_item_param_list.php
When there are multiple question versions:
1. Remove outdated versions from the scale.
2. Import the latest version.
=> GH-693 Fix import with multiple question versions

classes/catquiz.php, classes/local/model/model_item_param_list.php, classes/teststrategy/preselect_task/firstquestionselector.php, classes/teststrategy/preselect_task/updatepersonability.php
Use the model specified by the activeparamid value to update the ability parameter. No need to find the best model via AIC.
=> Update model selection during quiz attempt

classes/teststrategy/feedbackgenerator/customscalefeedback.php, tests/teststrategy/feedbackgenerator/customscalefeedback_test.php
=> GH-677 Sort feedback text by scale name

classes/teststrategy/feedbackgenerator/customscalefeedback.php, tests/teststrategy/feedbackgenerator/customscalefeedback_test.php
=> Dev david issue 678

classes/task/cancel_expired_attempts.php, tests/task/cancel_expired_attempts_test.php
=> Dev david issue 718

lang/de/local_catquiz.php
=> GH-731 Add missing German translation string

classes/teststrategy/feedbackgenerator.php, classes/teststrategy/feedbackgenerator/personabilities.php
=> Dev david issue 744

classes/teststrategy/preselect_task/updatepersonability.php
Es gibt nun auch eine neue Variable sdability, die analog zu meanablilty die Standardabweichung vergangener Versuche speichert.
=> implement sd from past attempts fix #754

classes/catquiz.php, classes/output/feedback_page.php, classes/shortcodes.php, classes/teststrategy/feedback_helper.php, feedback.php, templates/feedback_page.mustache
=> Dev david issue 757

classes/catcontext.php, classes/catmodel_info.php, classes/local/model/model_strategy.php, classes/local/model/model_strategy_factory.php
=> Dev david issue 798

classes/catquiz.php
When getting the response data, join on the person params of the selected $contextid
=> GH-807 prevent duplicate in response data
